export interface BuildWidgetScriptOptions {
  supabaseUrl: string;
  anonKey: string;
}

// Returns the full source of the embeddable chat widget as plain text
// (served by src/app/widget.js/route.ts). Kept as a string-returning
// function rather than a static asset so the Supabase URL/anon key can be
// interpolated server-side — the embed snippet a customer pastes stays a
// single <script src="…/widget.js"></script> tag with zero configuration.
//
// Only NEXT_PUBLIC_* values are ever interpolated here: the anon key is
// meant to be public (same trust level as any Supabase browser client) —
// the actual authorization happens server-side in supabase/functions/web-chat
// via the Origin allowlist, not by keeping this key secret.
//
// Deliberately dependency-free vanilla JS (no bundler in this repo builds a
// separate widget bundle) and mounted in a Shadow DOM so its styles can
// never leak into, or be broken by, the arbitrary third-party page it's
// embedded on.
export function buildWidgetScript(options: BuildWidgetScriptOptions): string {
  const supabaseUrl = JSON.stringify(options.supabaseUrl);
  const anonKey = JSON.stringify(options.anonKey);

  return [
    '(function () {',
    '  "use strict";',
    '  var SUPABASE_URL = ' + supabaseUrl + ';',
    '  var ANON_KEY = ' + anonKey + ';',
    '  var CHAT_URL = SUPABASE_URL + "/functions/v1/web-chat";',
    '  var SESSION_KEY = "wc_session_id";',
    '',
    '  function authHeaders() {',
    '    return { apikey: ANON_KEY, Authorization: "Bearer " + ANON_KEY };',
    '  }',
    '',
    '  function getSessionId() {',
    '    var id = window.localStorage.getItem(SESSION_KEY);',
    '    if (!id) {',
    '      id = crypto.randomUUID();',
    '      window.localStorage.setItem(SESSION_KEY, id);',
    '    }',
    '    return id;',
    '  }',
    '',
    '  function el(tag, className) {',
    '    var node = document.createElement(tag);',
    '    if (className) node.className = className;',
    '    return node;',
    '  }',
    '',
    '  function buildStyles(primaryColor, position) {',
    '    var side = position === "bottom-left" ? "left" : "right";',
    '    return [',
    '      ":host { all: initial; }",',
    '      "* { box-sizing: border-box; font-family: system-ui, -apple-system, sans-serif; }",',
    '      ".wc-bubble { position: fixed; bottom: 20px; " + side + ": 20px; width: 56px; height: 56px;",',
    '      "  border-radius: 9999px; background: " + primaryColor + "; color: #fff; border: none;",',
    '      "  cursor: pointer; box-shadow: 0 4px 14px rgba(0,0,0,0.25); font-size: 24px; z-index: 2147483000; }",',
    '      ".wc-panel { position: fixed; bottom: 88px; " + side + ": 20px; width: 340px; max-width: calc(100vw - 40px);",',
    '      "  height: 480px; max-height: calc(100vh - 120px); background: #fff; border-radius: 12px;",',
    '      "  box-shadow: 0 10px 40px rgba(0,0,0,0.25); display: none; flex-direction: column; overflow: hidden;",',
    '      "  z-index: 2147483000; }",',
    '      ".wc-panel.wc-open { display: flex; }",',
    '      ".wc-header { background: " + primaryColor + "; color: #fff; padding: 14px 16px; font-weight: 600; }",',
    '      ".wc-messages { flex: 1; overflow-y: auto; padding: 12px; display: flex; flex-direction: column; gap: 8px; }",',
    '      ".wc-msg { max-width: 85%; padding: 8px 12px; border-radius: 10px; font-size: 14px; line-height: 1.4; white-space: pre-wrap; }",',
    '      ".wc-msg-user { align-self: flex-end; background: " + primaryColor + "; color: #fff; }",',
    '      ".wc-msg-assistant { align-self: flex-start; background: #f1f3f5; color: #1a1a1a; }",',
    '      ".wc-msg-error { align-self: flex-start; background: #fdecec; color: #a61b1b; }",',
    '      ".wc-form { display: flex; gap: 8px; padding: 10px; border-top: 1px solid #eee; }",',
    '      ".wc-input { flex: 1; border: 1px solid #ddd; border-radius: 8px; padding: 8px 10px; font-size: 14px; }",',
    '      ".wc-send { background: " + primaryColor + "; color: #fff; border: none; border-radius: 8px;",',
    '      "  padding: 8px 14px; font-size: 14px; cursor: pointer; }",',
    '      ".wc-send:disabled { opacity: 0.6; cursor: default; }",',
    '    ].join("\\n");',
    '  }',
    '',
    '  function init(config) {',
    '    if (!config.enabled) return;',
    '',
    '    var host = el("div");',
    '    host.id = "wc-widget-host";',
    '    document.body.appendChild(host);',
    '    var shadow = host.attachShadow({ mode: "open" });',
    '',
    '    var style = document.createElement("style");',
    '    style.textContent = buildStyles(config.primaryColor, config.position);',
    '    shadow.appendChild(style);',
    '',
    '    var bubble = el("button", "wc-bubble");',
    '    bubble.type = "button";',
    '    bubble.setAttribute("aria-label", config.title || "Open chat");',
    '    bubble.textContent = "\\uD83D\\uDCAC";',
    '',
    '    var panel = el("div", "wc-panel");',
    '    var header = el("div", "wc-header");',
    '    header.textContent = config.title || "Chat with us";',
    '    var messages = el("div", "wc-messages");',
    '    var form = el("form", "wc-form");',
    '    var input = el("input", "wc-input");',
    '    input.type = "text";',
    '    input.placeholder = "Type a message…";',
    '    input.setAttribute("aria-label", "Message");',
    '    var send = el("button", "wc-send");',
    '    send.type = "submit";',
    '    send.textContent = "Send";',
    '',
    '    form.appendChild(input);',
    '    form.appendChild(send);',
    '    panel.appendChild(header);',
    '    panel.appendChild(messages);',
    '    panel.appendChild(form);',
    '    shadow.appendChild(panel);',
    '    shadow.appendChild(bubble);',
    '',
    '    function appendMessage(role, text) {',
    '      var msg = el("div", "wc-msg wc-msg-" + role);',
    '      msg.textContent = text;',
    '      messages.appendChild(msg);',
    '      messages.scrollTop = messages.scrollHeight;',
    '    }',
    '',
    '    var opened = false;',
    '    bubble.addEventListener("click", function () {',
    '      opened = !opened;',
    '      panel.classList.toggle("wc-open", opened);',
    '      if (opened && messages.children.length === 0 && config.welcomeMessage) {',
    '        appendMessage("assistant", config.welcomeMessage);',
    '      }',
    '    });',
    '',
    '    form.addEventListener("submit", function (event) {',
    '      event.preventDefault();',
    '      var text = input.value.trim();',
    '      if (!text) return;',
    '      appendMessage("user", text);',
    '      input.value = "";',
    '      input.disabled = true;',
    '      send.disabled = true;',
    '',
    '      fetch(CHAT_URL, {',
    '        method: "POST",',
    '        headers: Object.assign({ "Content-Type": "application/json" }, authHeaders()),',
    '        body: JSON.stringify({ sessionId: getSessionId(), message: text }),',
    '      })',
    '        .then(function (response) {',
    '          return response.json().then(function (data) {',
    '            return { ok: response.ok, data: data };',
    '          });',
    '        })',
    '        .then(function (result) {',
    '          if (result.ok) {',
    '            appendMessage("assistant", result.data.reply);',
    '          } else {',
    '            appendMessage("error", result.data.error || "Something went wrong. Please try again.");',
    '          }',
    '        })',
    '        .catch(function () {',
    '          appendMessage("error", "Couldn\'t reach the assistant. Please try again.");',
    '        })',
    '        .finally(function () {',
    '          input.disabled = false;',
    '          send.disabled = false;',
    '          input.focus();',
    '        });',
    '    });',
    '  }',
    '',
    '  fetch(CHAT_URL, { headers: authHeaders() })',
    '    .then(function (response) {',
    '      if (!response.ok) return null;',
    '      return response.json();',
    '    })',
    '    .then(function (config) {',
    '      if (!config) return;',
    '      init(config);',
    '    })',
    '    .catch(function () {',
    "      /* widget silently stays off the page if config can't be loaded */",
    '    });',
    '})();',
    '',
  ].join('\n');
}
